# Generated by Django 2.0.2 on 2020-12-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='u_id',
            field=models.IntegerField(default=1),
        ),
    ]
